spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:alike_db}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:DEBUG}

features:
  provider-submission-enabled: ${FEATURE_PROVIDER_SUBMISSION_ENABLED:false}
